# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: CI/CD 

# on:
#   push:
#     branches: [ "main" ] 
#   pull_request:
#     branches: [ "main" ]  

# jobs:
#   test-backend:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout du code
#       uses: actions/checkout@v4

#     - name: Installer Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: 20.16.0  

#     - name: Installer les dépendances Backend
#       run: |
#         cd Backend
#         npm install  # Installe les dépendances

#     - name: Exécuter les tests unitaires Backend
#       run: |
#         cd Backend
#         npm run test -- src/city/service/city.service.spec.ts  # Exécute les tests unitaires Jest

name: CI/CD deployment 

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd Frontend
        npm install


    - name: Build Frontend
      run: |
        cd Frontend
        npm run build

    - name: Deploy Frontend via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "Frontend/dist/"
        remote: "/var/www/html"




     

