# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: estlint/ prettier check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Vérifier la structure des fichiers
      run: ls -R

    - name: Installer les dépendances du Frontend
      run: |
        cd Frontend
        npm ci

    - name: Installer les dépendances du Backend
      run: |
        cd Backend
        npm ci

    - name: Lancer ESLint sur le Frontend
      run: |
        cd Frontend
        npm run lint

    - name: Lancer ESLint sur le Backend
      run: |
        cd Backend
        npm run lint
