name: CI/CD deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installer les dépendances Backend
        run: |
          set -e
          cd Backend
          npm install

      - name: Exécuter les tests unitaires Backend
        run: |
          set -e
          cd Backend
          npm run test -- src/city/service/city.service.spec.ts

      - name: Installer les dépendances Frontend
        run: |
          set -e
          cd Frontend
          npm install

      # - name: Exécuter les tests unitaires Frontend
      #   run: |
      #     cd Frontend
      #     npm run test -- src/services/trajet/trajetService.spec.ts

      - name: Créer le fichier .env
        run: |
          set -e
          cd Frontend
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" > .env
          echo "VITE_FRONTEND_PROD_URL=${{ secrets.VITE_FRONTEND_PROD_URL }}" >> .env
          echo "VITE_OPEN_ROUTE_SERVICE_KEY=${{ secrets.VITE_OPEN_ROUTE_SERVICE_KEY }}" >> .env
          echo "VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}" >> .env

      

      - name: Build Frontend
        run: |
          set -e
          cd Frontend
          npm run build

      - name: Déployer le fichier .env via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "Frontend/.env"
          target: "/var/www/html/"
          strip_components: 1

      - name: Vérifier le fichier .env
        run: cat /var/www/html/.env

        
      - name: Déployer le Frontend via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "Frontend/dist/*"
          target: "/var/www/html/"
          strip_components: 2
