# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI - Tests Backend

on:
  push:
    branches: [ "**" ]  # Déclenche les tests sur chaque commit dans toutes les branches
  pull_request:
    branches: [ "**" ]  # Déclenche les tests avant la fusion d'une PR dans n'importe quelle branche

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.16.0  

    - name: Installer les dépendances Backend
      run: |
        cd Backend
        npm install  # Installe les dépendances

    - name: Exécuter les tests unitaires Backend
      run: |
        cd Backend
        npm run test -- src/city/service/city.service.spec.ts  # Exécute les tests unitaires Jest



# Pour le backend
# Pour le frontend
scp .env user@votre-serveur:~/.config/app-secrets/.env.Frontend
     

