# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI - Tests Backend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Installer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.16.0  

    - name: Installer les dépendances Backend
      run: |
        cd Backend
        npm install  # Installe les dépendances

    - name: Exécuter les tests unitaires Backend
      run: |
        cd Backend
        npm run test  # Lance les tests unitaires Jest

     

